# Generated by Django 5.2.10 on 2026-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staff_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab Technician'), ('admin', 'Admin Staff')], default='nurse', max_length=50),
        ),
    ]
