# Generated by Django 5.2.10 on 2026-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_staffprofile_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('accountant', 'accountant'), ('lab', 'Lab Technician'), ('admin', 'Admin Staff')], default='nurse', max_length=50),
        ),
    ]
