# Generated by Django 5.2.10 on 2026-01-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_staffprofile_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('accountant', 'Accountant'), ('lab', 'Lab Technician'), ('admin', 'Admin Staff')], default='nurse', max_length=50),
        ),
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant', to='app1.staffprofile')),
            ],
        ),
    ]
