# Generated by Django 5.2.10 on 2026-01-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_staffprofile_staff_type_accountantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=100)),
                ('lab_type', models.CharField(help_text='Blood, Pathology, Radiology, Microbiology, etc.', max_length=100)),
                ('equipment_handled', models.TextField(blank=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='app1.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('rotational', 'Rotational')], max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to='app1.staffprofile')),
            ],
        ),
    ]
