# Generated by Django 5.2.10 on 2026-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_labtechnicianprofile_nurseprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtechnicianprofile',
            name='equipment_handled',
        ),
    ]
